version: '3.8'
services:
  frontend:
    image: hamzaAlaydi99/frontend:latest
    ports:
      - "80:80"
    restart: always

  backend:
    image: hamzaAlaydi99/backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
