name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm cache clean --force

      - name: Build production
        run: |
          rm -rf dist/
          npm run build
          ls -la dist/

      - name: Prepare EC2 Directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf /var/www/stephan-front/dist
            sudo mkdir -p /var/www/stephan-front/dist
            sudo chown -R ubuntu:ubuntu /var/www/stephan-front/dist
            sudo chmod -R 755 /var/www/stephan-front/dist

      - name: Deploy Frontend
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "/var/www/stephan-front/dist"
          overwrite: true
          strip_components: 0
          debug: true

      - name: Configure Permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/stephan-front/dist
            sudo find /var/www/stephan-front/dist -type d -exec chmod 755 {} \;
            sudo find /var/www/stephan-front/dist -type f -exec chmod 644 {} \;
            sudo systemctl restart nginx

      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/stephan-backend
            git pull origin main
            npm ci --production
            pm2 restart stephan-backend