name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm cache clean --force

      - name: Build production
        run: |
          npm run build
          ls -la dist/

      - name: Deploy files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "/var/www/stephan-front"
          overwrite: true
          strip_components: 0  # Changed from 1
          debug: true
          script: |
            sudo chown -R www-data:www-data /var/www/stephan-front
            sudo find /var/www/stephan-front -type d -exec chmod 755 {} \;
            sudo find /var/www/stephan-front -type f -exec chmod 644 {} \;

      - name: Restart server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            pm2 restart all
            sudo systemctl restart nginx