name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm cache clean --force

      - name: Build production
        run: |
          rm -rf dist/  # Remove old build
          npm run build
          ls -la dist/  # Verify new build output

      - name: Deploy files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*" # Deploy all files from dist/
          target: "/var/www/stephan-front/dist"
          overwrite: true # Ensure files are overwritten
          strip_components: 0 # Preserve directory structure
          debug: true # Enable debug logs
          script: |
            sudo rm -rf /var/www/stephan-front/*  # Delete old build before copying new files
            sudo chown -R www-data:www-data /var/www/stephan-front
            sudo find /var/www/stephan-front -type d -exec chmod 755 {} \;
            sudo find /var/www/stephan-front -type f -exec chmod 644 {} \;

      - name: Clean Old Files
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf /var/www/stephan-front/dist/*
            sudo chown -R www-data:www-data /var/www/stephan-front/dist
            sudo find /var/www/stephan-front/dist -type d -exec chmod 755 {} \;
            sudo find /var/www/stephan-front/dist -type f -exec chmod 644 {} \;

      - name: Restart server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/stephan-backend
            pm2 restart stephan-backend || pm2 start server.js --name "stephan-backend"
            sudo systemctl restart nginx
