name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm cache clean --force

      - name: Build production
        run: |
          rm -rf dist/
          npm run build
          ls -la dist/

      - name: Deploy Frontend
        uses: burnett01/rsync-deployments@5.2.3
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /var/www/stephan-front/dist/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Configure Permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/stephan-front/dist
            sudo find /var/www/stephan-front/dist -type d -exec chmod 755 {} \;
            sudo find /var/www/stephan-front/dist -type f -exec chmod 644 {} \;
            sudo systemctl restart nginx

      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/stephan-backend
            git pull origin main
            npm ci --production
            pm2 restart stephan-backend