name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm cache clean --force

      - name: Build production
        run: |
          npm run build
          ls -la dist/  # Verify build output

      - name: Deploy files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          source: "dist/"  # Changed from "client/dist/*"
          target: "/var/www/stephan-front"
          overwrite: true  # Ensure files are overwritten
          strip_components: 1  # Remove parent directory structure
          debug: true  # Enable debug logs

      - name: Restart server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/stephan-front
            pm2 restart all
            sudo systemctl restart nginx
